"""Initial migration

Revision ID: 89a9f4f2aa8c
Revises: 
Create Date: 2025-10-19 11:06:10.823123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a9f4f2aa8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('girl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('girl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_girl_name'), ['name'], unique=False)

    op.create_table('plot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hot_score', sa.Float(), nullable=False),
    sa.Column('crazy_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('plot_date', sa.DateTime(), nullable=True),
    sa.Column('girl_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['girl_id'], ['girl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_plot_date'), ['plot_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_plot_date'))

    op.drop_table('plot')
    with op.batch_alter_table('girl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_girl_name'))

    op.drop_table('girl')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
