"""Add timezone to user model

Revision ID: 93651bc13785
Revises: 89a9f4f2aa8c
Create Date: 2025-11-03 07:42:10.470206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93651bc13785'
down_revision = '89a9f4f2aa8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # MODIFICATION: Add server_default='UTC'
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=False, server_default='UTC'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
